name: atlas_sonoro
description: Atlas interactivo de subgéneros musicales de nicho con Flutter y Firebase.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.4.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  url_launcher: ^6.3.1
  firebase_auth: ^6.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/genres_seed.json
