name: atlas_sonoro
description: Atlas interactivo de subgeneros musicales de nicho con Flutter y Firebase.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/genres_seed.json
